Add palindrome check
MIT-Emerging-Talent/ET6-foundations-group-10 pull request #15
Opened 2024-12-31 18:36 UTC by emrebiyik

This pull request includes the following changes:
1. Implemented a palindrome checker function (is_palindrome) in the solutions directory.
2. Added corresponding unit tests in solutions/test_is_palindrome.py to ensure proper functionality and edge-case handling.
3. Reformatted files using Ruff to meet style and formatting requirements.
4. Renamed folders and files in the collaboration/minutes-of-meeting directory to comply with snake_case naming conventions.

Please review the changes and let me know if further improvements are needed. Thank you!

2025-01-01 18:55 UTC, oleksandr-maksymikhin requested changes
Added review in comments to each file

2025-01-01 18:55 UTC, oleksandr-maksymikhin commented on solutions/is_palindrome.py
Requirement “Assertions are documented (if there are any)” is broken.
There is no comment for defensive assertions in the line 35.

2025-01-01 18:55 UTC, oleksandr-maksymikhin commented on solutions/test_is_palindrome.py
Requirement “Test file is named `/tests/test_file_name.py`” is broken.
Move test_is_palindrome.py file into the directory /test.

Requirement “The code has no (reasonable) linting mistakes” is broken.
I have a linting mistake and can’t run test_is_palindrome.py
In the line 2
Instead of:
from is_palindrome import is_palindrome
use relative import:
from .is_palindrome import is_palindrome

Requirement “Only one assertion” is broken. There are 2 assertions in one test for some tests.
The list of tests with broken assertion rule:
def test_simple_palindrome(self)
def test_non_palindrome(self)
Leave only one assertion in the test.

Requirement “A clear docstring” is broken.
def test_simple_palindrome(self):
"""It should return True for simple palindromes."""
Docstring is unclear:
What is difference between simple and difficult palindromes? The string can be either palindrome or non-palindrome.
If you check here lower-case string, write the docstring like:
"""It should return True for lower-case palindromes."""
In case of correction docstring as proposed, correct also the test function name to match the test case, like test_lowercase_palindrome

Requirement “A clear docstring” is broken.
def test_mixed_case_palindrome(self):
"""It should handle mixed case palindromes."""
Docstring is unclear:
Handle – is unclear definition of behavior. Since the function return bool type, write “return True” instead “handle”
The docstring should looks like:
"""It should return True for palindrome with lower-case and upper-case characters."""
May be test name should be corrected.

Proposal for test coverage.
There are tests for lower-, upper-case symbols. There was no taste that also included in the string numbers, special characters. There is a requirement to test boundary cases. In my understanding boundary case in this situation is a string that includes lower-case symbols, upper-case symbols, numbers, special characters. Create the test that include all types of characters.

2025-01-01 18:55 UTC, oleksandr-maksymikhin commented on solutions/tests/__init__.py
Leave the file blank. There is \n character in the file now.

2025-01-03 16:18 UTC, emrebiyik commented on solutions/is_palindrome.py
Thank you for pointing this out. I agree that the assertion on line 35 is missing documentation. I will update the code with a comment to explain its purpose and ensure it aligns with the checklist requirement.

2025-01-03 17:41 UTC, emrebiyik commented on solutions/test_is_palindrome.py
Thank you for your detailed feedback. I have carefully addressed each point as follows:

1. Test file location: The test_is_palindrome.py file has been moved to the solutions/tests directory as required.

2. Linting issue: The import statement has been updated to use relative import:
                             from .is_palindrome import is_palindrome

3. One assertion per test: Test functions with multiple assertions, such as test_simple_palindrome and test_non_palindrome, have been split into separate test cases, each containing only one assertion.
	
4. Clear docstrings: Docstrings have been clarified to better describe the test cases. For example:
	•	"It should return True for simple palindromes." → "It should return True for lower-case palindromes."
	•	"It should handle mixed case palindromes." → "It should return True for palindromes with lower-case and upper-case characters."
	
5. Test coverage: New test cases have been added to include boundary cases, such as strings with numbers, special characters, and mixed character types.

Please let me know if there are any additional suggestions. Thank you again for your feedback!

2025-01-03 18:00 UTC, emrebiyik commented on solutions/tests/__init__.py
I have addressed the issue by ensuring the __init__.py file in the solutions/tests directory is completely blank, as requested. Any unnecessary characters (e.g., \n) have been removed.

2025-01-03 18:31 UTC, emrebiyik commented
The Pull Request has been updated with the latest changes. All requested modifications have been implemented in the most recent commit. Please review the updates and let me know if further changes are required.

2025-01-06 07:22 UTC, oleksandr-maksymikhin requested changes

2025-01-06 07:22 UTC, oleksandr-maksymikhin commented on solutions/is_palindrome.py
When doing predictive stepping I have identified an issue with wring strategy implementation.
I tried two edge tests for special characters palindrome:
test_1 = is_palindrome("$+$")
test_2 = is_palindrome("$+#")
Both tests returned True, but test_1 is palindrome when test_2 is non-palindrome.

The issue is in the line 39
Operator isalnum() return True if the character is alpha-numeric. 
Since special characters are not alpha-numeric they are skipped and, in both cases, the variable normalized = “”
Since “” equal reversed “” function result is True, but for the test_2 = is_palindrome("$+#") function result should be false.

2025-01-06 07:22 UTC, oleksandr-maksymikhin commented on solutions/tests/test_is_palindrome.py
Add docstring with description of test module like in the file is_palindrome.py.

2025-01-06 14:30 UTC, emrebiyik commented on solutions/is_palindrome.py
The issue with isalnum() ignoring special characters has been resolved. The normalization logic now considers special characters, correctly identifying $+$ as a palindrome while $+# is not. Test cases have been updated to include these edge cases.

2025-01-06 14:31 UTC, emrebiyik commented on solutions/tests/test_is_palindrome.py
> Add docstring with description of test module like in the file is_palindrome.py.

A module-level docstring has been added to the test_is_palindrome.py file, describing the purpose of the test module and the cases it covers. This ensures clarity and aligns with the format used in is_palindrome.py.

2025-01-06 14:42 UTC, oleksandr-maksymikhin approved these changes
All the issues were resolved

2025-01-06 14:51 UTC, merged